[package]
name = "toad"
version = "0.7.16"
edition = "2024"

[dependencies]
crossterm = "0.29.0"
regex = "1.11.1"
reqwest = "0.12.23"
tokio = { version = "1.47.1", features = ["rt", "macros", "rt-multi-thread"] }
